version: '3'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    container_name: 'api_copybase'
    volumes:
      - './data:/database.sqlite'
    networks:
      - copybase_network

networks:
  copybase_network:
